name: CI to test if the docker container can be build

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
	  load: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pysages-hoomd:test

      - name: Test the build container
        run: |
          docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/pysages-hoomd:test bash -c "python3 -c 'import hoomd; import hoomd.dlext'"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
